name: todo
description: To-Do
labels: ["kind: todo"]
body:
  - type: markdown
    attributes:
      value: |

        Before write To-Do issue, check
        * Not [duplicated](https://github.com/hannbyul/notapy/issues?q=is%3Aopen+is%3Aissue+label%3Akind%3A%20todo)

  - type: textarea
    attributes:
      label: Description
      description: Description of To-Do
    validations:
      required: true
