name: API workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up python/env
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Save secrets to .env
        run: |
          echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> .env &&
          echo "DATABASE_TOKEN=${{ secrets.DATABASE_TOKEN }}" >> .env &&
          echo "PAGE_TOKEN=${{ secrets.PAGE_TOKEN }}" >> .env

      - name: Run workflow
        run: |
          python notisql/workflow.py
